// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adjustBrightness.proto

package grpc.cadanielLightingSystem;

public final class BrightnessServiceImpl {
  private BrightnessServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cadanielLightingSystem_BrightnessRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cadanielLightingSystem_BrightnessRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cadanielLightingSystem_BrightnessResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cadanielLightingSystem_BrightnessResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026adjustBrightness.proto\022\026cadanielLighti" +
      "ngSystem\"?\n\021BrightnessRequest\022\030\n\020brightn" +
      "ess_level\030\001 \001(\005\022\020\n\010location\030\002 \001(\t\"H\n\022Bri" +
      "ghtnessResponse\022\020\n\010location\030\001 \001(\t\022\017\n\007suc" +
      "cess\030\002 \001(\010\022\017\n\007message\030\003 \001(\t2\202\001\n\021Brightne" +
      "ssService\022m\n\020adjustBrightness\022).cadaniel" +
      "LightingSystem.BrightnessRequest\032*.cadan" +
      "ielLightingSystem.BrightnessResponse(\0010\001" +
      "B6\n\033grpc.cadanielLightingSystemB\025Brightn" +
      "essServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cadanielLightingSystem_BrightnessRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cadanielLightingSystem_BrightnessRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cadanielLightingSystem_BrightnessRequest_descriptor,
        new java.lang.String[] { "BrightnessLevel", "Location", });
    internal_static_cadanielLightingSystem_BrightnessResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cadanielLightingSystem_BrightnessResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cadanielLightingSystem_BrightnessResponse_descriptor,
        new java.lang.String[] { "Location", "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
