// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adjustBrightness.proto

package grpc.cadanielLightingSystem;

public interface BrightnessResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cadanielLightingSystem.BrightnessResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>bool success = 2;</code>
   */
  boolean getSuccess();

  /**
   * <pre>
   * Message indicating success or failure
   * </pre>
   *
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Message indicating success or failure
   * </pre>
   *
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
