// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adjustBrightness.proto

package grpc.cadanielLightingSystem;

public interface BrightnessRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cadanielLightingSystem.BrightnessRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 brightness_level = 1;</code>
   */
  int getBrightnessLevel();

  /**
   * <code>string location = 2;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 2;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
