// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: turnOnOffLights.proto

package grpc.cadanielLightingSystem;

public interface CheckLightsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cadanielLightingSystem.CheckLightsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string roomNumber = 1;</code>
   */
  java.lang.String getRoomNumber();
  /**
   * <code>string roomNumber = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomNumberBytes();
}
