// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: turnOnOffLights.proto

package grpc.cadanielLightingSystem;

public interface CheckLightsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cadanielLightingSystem.CheckLightsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool available = 1;</code>
   */
  boolean getAvailable();
}
