// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: turnOnOffLights.proto

package grpc.cadanielLightingSystem;

public final class TurnOnOffLightsImpl {
  private TurnOnOffLightsImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cadanielLightingSystem_CheckLightsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cadanielLightingSystem_CheckLightsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cadanielLightingSystem_CheckLightsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cadanielLightingSystem_CheckLightsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025turnOnOffLights.proto\022\026cadanielLightin" +
      "gSystem\"(\n\022CheckLightsRequest\022\022\n\nroomNum" +
      "ber\030\001 \001(\t\"(\n\023CheckLightsResponse\022\021\n\tavai" +
      "lable\030\001 \001(\0102y\n\017TurnOnOffLights\022f\n\013checkL" +
      "ights\022*.cadanielLightingSystem.CheckLigh" +
      "tsRequest\032+.cadanielLightingSystem.Check" +
      "LightsResponseB4\n\033grpc.cadanielLightingS" +
      "ystemB\023TurnOnOffLightsImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cadanielLightingSystem_CheckLightsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cadanielLightingSystem_CheckLightsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cadanielLightingSystem_CheckLightsRequest_descriptor,
        new java.lang.String[] { "RoomNumber", });
    internal_static_cadanielLightingSystem_CheckLightsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cadanielLightingSystem_CheckLightsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cadanielLightingSystem_CheckLightsResponse_descriptor,
        new java.lang.String[] { "Available", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
