// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roomBookingService.proto

package grpc.cadanielMeetingRoomBookingSystem;

public final class RoomBookingServiceImpl {
  private RoomBookingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cadanielMeetingRoomBookingSystem_RoomBookingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cadanielMeetingRoomBookingSystem_RoomBookingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cadanielMeetingRoomBookingSystem_RoomBookingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cadanielMeetingRoomBookingSystem_RoomBookingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030roomBookingService.proto\022 cadanielMeet" +
      "ingRoomBookingSystem\"X\n\022RoomBookingReque" +
      "st\022\014\n\004date\030\001 \001(\t\022\014\n\004time\030\002 \001(\t\022\020\n\010durati" +
      "on\030\003 \001(\t\022\024\n\014requirements\030\004 \001(\t\"+\n\023RoomBo" +
      "okingResponse\022\024\n\014confirmation\030\001 \001(\t2\217\001\n\022" +
      "RoomBookingService\022y\n\010bookRoom\0224.cadanie" +
      "lMeetingRoomBookingSystem.RoomBookingReq" +
      "uest\0325.cadanielMeetingRoomBookingSystem." +
      "RoomBookingResponse(\001BA\n%grpc.cadanielMe" +
      "etingRoomBookingSystemB\026RoomBookingServi" +
      "ceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cadanielMeetingRoomBookingSystem_RoomBookingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cadanielMeetingRoomBookingSystem_RoomBookingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cadanielMeetingRoomBookingSystem_RoomBookingRequest_descriptor,
        new java.lang.String[] { "Date", "Time", "Duration", "Requirements", });
    internal_static_cadanielMeetingRoomBookingSystem_RoomBookingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cadanielMeetingRoomBookingSystem_RoomBookingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cadanielMeetingRoomBookingSystem_RoomBookingResponse_descriptor,
        new java.lang.String[] { "Confirmation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
