// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roomBookingService.proto

package grpc.cadanielMeetingRoomBookingSystem;

public interface RoomBookingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cadanielMeetingRoomBookingSystem.RoomBookingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string date = 1;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 1;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string time = 2;</code>
   */
  java.lang.String getTime();
  /**
   * <code>string time = 2;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <code>string duration = 3;</code>
   */
  java.lang.String getDuration();
  /**
   * <code>string duration = 3;</code>
   */
  com.google.protobuf.ByteString
      getDurationBytes();

  /**
   * <code>string requirements = 4;</code>
   */
  java.lang.String getRequirements();
  /**
   * <code>string requirements = 4;</code>
   */
  com.google.protobuf.ByteString
      getRequirementsBytes();
}
