// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roomBookingService.proto

package grpc.cadanielMeetingRoomBookingSystem;

public interface RoomBookingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cadanielMeetingRoomBookingSystem.RoomBookingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmation = 1;</code>
   */
  java.lang.String getConfirmation();
  /**
   * <code>string confirmation = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmationBytes();
}
