// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roomAvailability.proto

package grpc.cadanielMeetingRoomBookingSystem;

public interface RoomAvailabilityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cadanielMeetingRoomBookingSystem.RoomAvailabilityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool available = 1;</code>
   */
  boolean getAvailable();
}
