// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roomavailability.proto

package grpc.cadanielMeetingRoomBookingSystem;

public interface RoomAvailabilityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cadanielMeetingRoomBookingSystem.RoomAvailabilityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string roomNumber = 1;</code>
   */
  java.lang.String getRoomNumber();
  /**
   * <code>string roomNumber = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomNumberBytes();
}
