// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: camaraMonitoring.proto

package grpc.cadanielSecuritySystem;

public final class CamaraServiceImpl {
  private CamaraServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cadanielSecuritySystem_CheckCamaraRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cadanielSecuritySystem_CheckCamaraRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cadanielSecuritySystem_CheckCamaraResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cadanielSecuritySystem_CheckCamaraResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026camaraMonitoring.proto\022\026cadanielSecuri" +
      "tySystem\"\'\n\022CheckCamaraRequest\022\021\n\tcamara" +
      "_id\030\001 \001(\t\"6\n\023CheckCamaraResponse\022\021\n\tcama" +
      "ra_id\030\001 \001(\t\022\014\n\004data\030\002 \001(\t2y\n\rCamaraServi" +
      "ce\022h\n\013checkCamara\022*.cadanielSecuritySyst" +
      "em.CheckCamaraRequest\032+.cadanielSecurity" +
      "System.CheckCamaraResponse0\001B2\n\033grpc.cad" +
      "anielSecuritySystemB\021CamaraServiceImplP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cadanielSecuritySystem_CheckCamaraRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cadanielSecuritySystem_CheckCamaraRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cadanielSecuritySystem_CheckCamaraRequest_descriptor,
        new java.lang.String[] { "CamaraId", });
    internal_static_cadanielSecuritySystem_CheckCamaraResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cadanielSecuritySystem_CheckCamaraResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cadanielSecuritySystem_CheckCamaraResponse_descriptor,
        new java.lang.String[] { "CamaraId", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
