// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lockUnLockDoors.proto

package grpc.cadanielSecuritySystem;

public interface CheckDoorsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cadanielSecuritySystem.CheckDoorsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool available = 1;</code>
   */
  boolean getAvailable();
}
