// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lockUnLockDoors.proto

package grpc.cadanielSecuritySystem;

public interface CheckDoorsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cadanielSecuritySystem.CheckDoorsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string roomNumber = 1;</code>
   */
  java.lang.String getRoomNumber();
  /**
   * <code>string roomNumber = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomNumberBytes();
}
