// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: camaraMonitoring.proto

package grpc.cadanielSecuritySystem;

public interface CheckCamaraRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cadanielSecuritySystem.CheckCamaraRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string camara_id = 1;</code>
   */
  java.lang.String getCamaraId();
  /**
   * <code>string camara_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCamaraIdBytes();
}
