// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: camaraMonitoring.proto

package grpc.cadanielSecuritySystem;

public interface CheckCamaraResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cadanielSecuritySystem.CheckCamaraResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string camara_id = 1;</code>
   */
  java.lang.String getCamaraId();
  /**
   * <code>string camara_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCamaraIdBytes();

  /**
   * <code>string data = 2;</code>
   */
  java.lang.String getData();
  /**
   * <code>string data = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
