// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lockUnLockDoors.proto

package grpc.cadanielSecuritySystem;

public final class LockUnlockDoorsImpl {
  private LockUnlockDoorsImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cadanielSecuritySystem_CheckDoorsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cadanielSecuritySystem_CheckDoorsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cadanielSecuritySystem_CheckDoorsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cadanielSecuritySystem_CheckDoorsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025lockUnLockDoors.proto\022\026cadanielSecurit" +
      "ySystem\"\'\n\021CheckDoorsRequest\022\022\n\nroomNumb" +
      "er\030\001 \001(\t\"\'\n\022CheckDoorsResponse\022\021\n\tavaila" +
      "ble\030\001 \001(\0102v\n\017LockUnlockDoors\022c\n\ncheckDoo" +
      "rs\022).cadanielSecuritySystem.CheckDoorsRe" +
      "quest\032*.cadanielSecuritySystem.CheckDoor" +
      "sResponseB4\n\033grpc.cadanielSecuritySystem" +
      "B\023LockUnlockDoorsImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cadanielSecuritySystem_CheckDoorsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cadanielSecuritySystem_CheckDoorsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cadanielSecuritySystem_CheckDoorsRequest_descriptor,
        new java.lang.String[] { "RoomNumber", });
    internal_static_cadanielSecuritySystem_CheckDoorsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cadanielSecuritySystem_CheckDoorsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cadanielSecuritySystem_CheckDoorsResponse_descriptor,
        new java.lang.String[] { "Available", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
